# -*- coding: utf-8 -*-
"""create_db

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FkNjTqM1X1wX2NXt9GSfCjzJ_FQLLcGy
"""

import sqlite3

def create_database():
    conn = sqlite3.connect("ebooks.db")
    cursor = conn.cursor()

    cursor.execute("""
    CREATE TABLE IF NOT EXISTS books (
        book_id INTEGER PRIMARY KEY AUTOINCREMENT,
        title TEXT,
        author TEXT,
        language TEXT,
        description TEXT,
        file_path TEXT
    )
    """)
    cursor.execute("""
    CREATE TABLE IF NOT EXISTS tags (
        tag_id INTEGER PRIMARY KEY AUTOINCREMENT,
        book_id INTEGER,
        tag TEXT,
        FOREIGN KEY (book_id) REFERENCES books(book_id)
    )
    """)

    cursor.executemany("""
    INSERT INTO books (title, author, language, description, file_path)
    VALUES (?, ?, ?, ?, ?)
    """, [
        ('Thirukkural', 'Thiruvalluvar', 'Tamil', 'Ancient Tamil couplets', '/ebooks/thirukkural.pdf'),
        ('Gitanjali', 'Rabindranath Tagore', 'Bengali', 'Poems of devotion', '/ebooks/gitanjali.pdf'),
        ('Panchatantra', 'Vishnu Sharma', 'Sanskrit', 'Stories with morals', '/ebooks/panchatantra.pdf')
    ])

    conn.commit()
    conn.close()