# -*- coding: utf-8 -*-
"""create_db

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FkNjTqM1X1wX2NXt9GSfCjzJ_FQLLcGy
"""

import sqlite3

def create_database():
    conn = sqlite3.connect("ebooks.db")
    cursor = conn.cursor()

    cursor.execute("""
    CREATE TABLE IF NOT EXISTS books (
        book_id INTEGER PRIMARY KEY AUTOINCREMENT,
        title TEXT,
        author TEXT,
        language TEXT,
        description TEXT,
        file_path TEXT
    )
    """)
    cursor.execute("""
    CREATE TABLE IF NOT EXISTS tags (
        tag_id INTEGER PRIMARY KEY AUTOINCREMENT,
        book_id INTEGER,
        tag TEXT,
        FOREIGN KEY (book_id) REFERENCES books(book_id)
    )
    """)

    cursor.executemany("""
    INSERT INTO books (title, author, language, description, file_path)
    VALUES (?, ?, ?, ?, ?)
    """, [
        ('Thirukkural', 'Thiruvalluvar', 'Tamil', 'Ancient Tamil couplets', 'https://www.scribd.com/document/456942075/%E0%AE%A4%E0%AE%BF%E0%AE%B0%E0%AF%81%E0%AE%95-%E0%AE%95%E0%AF%81%E0%AE%B1%E0%AE%B3-%E0%AE%8E%E0%AE%B3%E0%AE%BF%E0%AE%AF-%E0%AE%89%E0%AE%B0%E0%AF%88-pdf'),
        ('Gitanjali', 'Rabindranath Tagore', 'Bengali', 'Poems of devotion', 'https://archive.org/details/gitanjali00unse/page/n21/mode/2up'),
        ('Panchatantra', 'Vishnu Sharma', 'Sanskrit', 'Stories with morals', 'https://archive.org/details/PanchatantraSanskritHindi-JpMishra1910')
    ])

    conn.commit()
    conn.close()
